# Generated by Django 3.2.4 on 2022-06-12 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220612_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cadre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_first_appointment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_first_appointment_nuc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_present_appointment',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_present_posting',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='employment_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='employment_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='grade_level',
            field=models.IntegerField(default=21),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='ipps_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_dhr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_es',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='staff_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='staff_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='step',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='title',
            field=models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS')], max_length=5),
        ),
    ]
