# Generated by Django 3.2.4 on 2022-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_first_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_first_appointment_nuc',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_present_appointment',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_of_present_posting',
            field=models.DateField(null=True),
        ),
    ]
