# Generated by Django 3.2.4 on 2022-06-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220617_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='grade_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='step',
            field=models.IntegerField(null=True),
        ),
    ]
