# Generated by Django 3.2.4 on 2022-06-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20220618_1104'),
        ('accounts', '0009_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
