# Generated by Django 3.2.4 on 2022-06-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='employee/profile_picture'),
        ),
    ]
