# Generated by Django 3.2.4 on 2022-06-19 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_auto_20220618_1104'),
        ('accounts', '0012_alter_staffprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='staff/profile_picture'),
        ),
    ]
