# Generated by Django 3.2.4 on 2022-06-18 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0004_auto_20220618_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='staffs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
