# Generated by Django 3.2.4 on 2022-06-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_department_staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='director',
        ),
        migrations.RemoveField(
            model_name='department',
            name='staffs',
        ),
    ]
