# Generated by Django 3.2.4 on 2022-06-19 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0006_auto_20220618_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('no_of_days', models.CharField(blank=True, max_length=15, null=True)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=255)),
                ('leave_purpose', models.CharField(choices=[('ANNUAL LEAVE', 'ANNUAL LEAVE'), ('CASUAL LEAVE', 'CASUAL LEAVE'), ('SICK LEAVE', 'SICK LEAVE'), ('MATERNITY LEAVE', 'MATERNITY LEAVE'), ('OTHERS', 'OTHERS')], default='ANNUAL', max_length=255)),
                ('additional_note', models.TextField(blank=True, max_length=10000, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
