# Generated by Django 3.2.4 on 2022-06-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved_by_DHR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leave',
            name='sent_to_DHR',
            field=models.BooleanField(default=False),
        ),
    ]
