# Generated by Django 3.2.4 on 2022-06-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_auto_20220619_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('SENT TO DHR', 'SENT TO DHR'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=255),
        ),
    ]
