# Generated by Django 3.2.14 on 2022-07-14 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
