# Generated by Django 3.2.14 on 2022-07-14 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_director_staff'),
        ('department', '0014_alter_query_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffprofile'),
        ),
    ]
