# Generated by Django 3.2.14 on 2022-07-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_alter_query_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='recommendation_to_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='sanction_or_warning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='query',
            name='staff_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('SENT TO DHR', 'SENT TO DHR'), ('SENT TO EC', 'SENT TO EC'), ('QUERY ISSUED', 'QUERY ISSUED'), ('STAFF RESPONDED', 'STAFF RESPONDED'), ('RESOLVED', 'RESOLVED')], default='SENT TO DHR', max_length=255),
        ),
    ]
